amcl:
  ros__parameters:
    use_sim_time: true
    tf_broadcast: true
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_footprint
    scan_topic: /scan_front_raw
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    max_beams: 180
    update_min_d: 0.2
    update_min_a: 0.03
    set_initial_pose: true
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    initial_pose.yaw: 0.0


# -------------------------
# BT Navigator
# -------------------------
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map          
    robot_base_frame: base_footprint
    odom_topic: /odometry/filtered
    default_nav_to_pose_bt_xml: "/home/nhan/Documents/ros/project/src/nav2_simple_navigation/behavior_tree/navigate_smart.xml"
   
# -------------------------
# Planner Server
# -------------------------
planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 10.0

    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: true

# -------------------------
# Controller Server (MPPI)
# -------------------------
controller_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: true
    controller_frequency: 20.0
    costmap_update_timeout: 0.3
    min_x_velocity_threshold: 0.05
    min_y_velocity_threshold: 0.01
    odom_topic: /odometry/filtered
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["MPPI"]


    # current_progress_checker: "progress_checker"
    # current_goal_checker: "general_goal_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 6.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.08
      path_length_tolerance: 0.8
    # RegulatedPurePursuitController
    RPPC:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      use_collision_detection: true
      desired_linear_velocity: 1.0
      lookahead_dist: 0.6       # Crucial: smaller = tighter turns, larger = smoother
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.5
      transform_tolerance: 0.5
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: false # Set to false since you're in an empty space
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.1
    
    # MPPI
    MPPI:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 30 # So buoc du doan, horizon ngan hon de phan ung nhanh
      model_dt: 0.10 # thoi gian moi buoc
      batch_size: 1000 # So quy dao sample
      vx_std: 1.5 # Noise: tang de MPPI explore du van toc tien/lui ro hon
      vy_std: 0.01 # Giu MPPI on dinh, tranh suy bien
      wz_std: 0.6 # Nois
      # Giu doi xung am/duong de robot van co the di lui.
      # Khong dat vx_min duong neu can reverse.
      vx_max: 1.8 # limit linear speed
      vx_min: -1.5 # limit linear speed
      vy_max: 0.05 # Gioi han ngang nho de tranh NaN
      vy_min: -0.05 # Gioi han ngang nho de tranh NaN
      wz_min: -1.5 # limit angular speed 
      wz_max: 1.5 # limit angular speed 
      ax_max: 3.0 # limit accel
      ay_max: 0.1 # Nho, du de MPPI khong bi suy bien
      az_max: 3.0 # limit accel
      iteration_count: 2 # Tang do on dinh khi toi uu
      prune_distance: 1.7 # Khoảng cách để cắt bỏ phần path đã đi qua
      transform_tolerance: 0.5 # Thời gian chấp nhận trễ
      temperature: 0.4 # Tang nhe de tranh bi ket vao quy dao qua "nhat"
      gamma: 0.012 # Giam phat control effort de robot dam ra lenh lon hon
      motion_model: "Omni"
      visualize: true # Có publish trajectory để debug không
      critics: [
        "ConstraintCritic",
        "CostCritic",
        "GoalCritic",
        "GoalAngleCritic",
        "PathAlignCritic",
        "PathFollowCritic",
        "PathAngleCritic",
        "PreferForwardCritic"
      ]

      # ConstraintCritic phat quy dao kho (gat)
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0

      #  CostCritic manh -> Robot so vung cost cao (obs)
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.5
        critical_cost: 250.0
        consider_footprint: true

      # Chấm điểm quỹ đạo dựa trên khoảng cách tới goal
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 1.0

      # Chấm điểm quỹ đạo dựa trên sai lệch góc (yaw) so với goal
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        threshold_to_consider: 1.0

      # Chấm điểm quỹ đạo dựa trên độ thẳng hàng với global path
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 0.2
        threshold_to_consider: 0.5
        offset_from_furthest: 20

      # Chấm điểm dựa trên khoảng cách của robot tới path
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 0.9
        threshold_to_consider: 1.0

      # Phạt nếu robot không quay theo hướng của path
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 0.5
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: false



# -------------------------
# Global Costmap
# -------------------------
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true

      global_frame: map
      robot_base_frame: base_footprint
      footprint: "[[0.30, 0.20], [0.30, -0.20], [-0.30, -0.20], [-0.30, 0.20]]"
      footprint_padding: 0.08

      update_frequency: 5.0
      publish_frequency: 2.0
      always_send_full_costmap: true

      rolling_window: false
      width: 10
      height: 10
      resolution: 0.05

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan_front_raw
          data_type: "LaserScan"
          clearing: true
          marking: true
          obstacle_max_range: 8.5
          raytrace_max_range: 10.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.43 # Tang de robot dam ra lenh lon hon khi gan obstacle, giam toc do de tranh va cham
        cost_scaling_factor: 1.5


# -------------------------
# Local Costmap
# -------------------------
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 10.0
      publish_frequency: 5.0
      always_send_full_costmap: true
      transform_tolerance: 0.5
      global_frame: odom
      robot_base_frame: base_footprint
      footprint: "[[0.30, 0.20], [0.30, -0.20], [-0.30, -0.20], [-0.30, 0.20]]"
      footprint_padding: 0.0


      resolution: 0.05

      # IMPORTANT for local behavior
      rolling_window: true
      width: 12
      height: 12

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: false
        observation_sources: scan
        scan:
          topic: /scan_front_raw
          data_type: "LaserScan"
          clearing: true
          marking: true
          obstacle_min_range: 0.0
          obstacle_max_range: 3.0
          raytrace_min_range: 0.0
          raytrace_max_range: 4.5
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          inf_is_valid: true
          observation_persistence: 0.5
          expected_update_rate: 0.0
      # plugins: ["inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.43
        cost_scaling_factor: 1.48

# -------------------------
# Recovery Server
# -------------------------

recoveries_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"
    global_frame: odom
    robot_base_frame: base_footprint
    transform_timeout: 0.1
    use_realtime_priority: false

# -------------------------
# Lifecycle Manager
# -------------------------
lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true

    node_names: [
      'global_costmap/global_costmap',
      'local_costmap/local_costmap',
      "planner_server",
      "controller_server",
      "bt_navigator"
    ]

    bond_timeout: 10.0
    attempt_respawn_reconnection: true
    bond_respawn_max_duration: 10.0
